events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;
    server {
        listen 80;
        server_name _;

        client_max_body_size 50M;

        # =========================
        # Default root → Laravel public
        # =========================
        root /var/www/backend/public;
        index index.php index.html;

        # =========================
        # API (Laravel)
        # =========================

        # Handle /api (no slash)
        location = /api {
            return 301 /api/;
        }

        # All API routes
        location ^~ /api/ {
            try_files $uri $uri/ /index.php?$query_string;
        }

        # =========================
        # Webhook (Laravel)
        # =========================
        location ^~ /webhook/ {
            root /var/www/backend/public;
            try_files $uri $uri/ /index.php?$query_string;
        }

        # =========================
        # PHP-FPM
        # =========================
        location ~ \.php$ {
            include fastcgi_params;

            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $document_root;

            fastcgi_pass php-fpm:9000;
        }

        # =========================
        # Frontend (React)
        # =========================
        location / {
            root /var/www/frontend;
            try_files $uri $uri/ /index.html;
        }
    }

}